import { RuleItem } from "../validate.type"

export const demoProps = {
  editable: true,
  fieldLayout: {
    span: 12,
    labelStyle: {
      width: "200px",
    },
    wrapperStyle: {
      width: "calc(100% - 200px)",
    },
  },
  fields: [
    {
      key: "input",
      label: "input",
      type: "input",
      required: true,
      br: false,
      allowClear: true,
      helpText: "请输入",
      hidden: true,
      // prefix: <Icon type="mobile" />,
      // onChange: (...args: any[]) => {
      //   console.log(args)
      // },
    },
    {
      key: "password",
      label: "password",
      type: "password",
      required: true,
      br: false,
      allowClear: true,
      helpText: "请输入",
      hidden: false,
      // prefix: <Icon type="mobile" />,
    },
    {
      key: "password1",
      label: "password1",
      type: "password",
      required: true,
      br: false,
      allowClear: true,
      helpText: "请输入",
      hidden: false,
      validator: (value: any, op: { rule: RuleItem; values: { password: any } }) => {
        return new Promise(resolve => {
          if (value == op.values.password) {
            resolve({ key: op.rule.key, valid: true })
          } else {
            resolve({ key: op.rule.key, valid: false, message: "两次输入的密码不一致" })
          }
        })
      },
    },
    {
      key: "textarea",
      label: "textarea",
      type: "textarea",
      required: true,
      br: true,
      allowClear: true,
      style: { width: "100%" },
    },
    {
      key: "switch",
      label: "switch",
      type: "switch",
      required: true,
    },
    {
      key: "checkbox",
      label: "checkbox",
      type: "checkbox",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "checkboxGroup",
      label: "checkboxGroup",
      type: "checkboxGroup",
      required: true,
      editable: true,
      br: false,
      optionKey: "checkboxGroup",
      options: [
        { label: "test1", value: "test1" },
        { label: "test2", value: "test2" },
      ],
    },
    {
      key: "autoComplete",
      label: "autoComplete",
      type: "autoComplete",
      dataSource: ["11111", "test1111"],
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "cascader",
      label: "cascader",
      type: "cascader",
      options: [
        { label: "test1", value: "test1", children: [{ label: "test2", value: "test2" }] },
        { label: "test333", value: "test3", children: [{ label: "test444", value: "test4" }] },
      ],
      required: true,
      editable: false,
      br: false,
    },
    {
      key: "datePicker",
      label: "datePicker",
      type: "datePicker",
      required: true,
      editable: false,
      br: false,
    },
    {
      key: "monthPicker",
      label: "monthPicker",
      type: "monthPicker",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "weekPicker",
      label: "weekPicker",
      type: "weekPicker",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "rangePicker",
      label: "rangePicker",
      type: "rangePicker",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "duration",
      label: "duration",
      type: "duration",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "timeRange",
      label: "timeRange",
      type: "timeRange",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "inputNumber",
      label: "inputNumber",
      type: "inputNumber",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "radioGroup",
      label: "radioGroup",
      type: "radioGroup",
      required: true,
      editable: false,
      br: false,
      options: [
        { label: "test1", value: "test1" },
        { label: "test2", value: "test2" },
      ],
    },
    {
      key: "select",
      label: "select",
      type: "select",
      required: true,
      editable: false,
      br: false,
      options: [
        { label: "test1", value: "test1" },
        { label: "test2", value: "test2" },
        { label: "test3", value: "test3" },
      ],
      mode: "multiple",
      // onChange: (v: any, o: {}, op: { props: { data: any } }) => {
      //   console.log(v, op.props)
      // },
    },
    {
      key: "treeSelect",
      label: "treeSelect",
      type: "treeSelect",
      required: true,
      editable: true,
      br: false,
      options: [
        { label: "test111111", value: "test1", children: [{ label: "test3", value: "test3" }] },
        { label: "test2", value: "test2" },
      ],
    },
    {
      key: "timePicker",
      label: "timePicker",
      type: "timePicker",
      required: true,
      editable: true,
      br: false,
    },
    {
      key: "upload",
      label: "upload",
      type: "upload",
      required: true,
      editable: true,
      rules: [],
      br: true,
    },
    {
      key: "upload2",
      label: "upload2",
      type: "upload",
      required: true,
      editable: true,
      rules: [],
      uploadType: "file",
      br: false,
    },
    {
      key: "array",
      label: "array",
      type: "array",
      required: true,
      editable: true,
      span: 24,
      br: true,
      fieldLayout: { span: 8, wrapperStyle: { width: "100%" } },
      minLength: 2,
      maxLength: 3,
      fields: [
        {
          type: "inputGroup",
          span: 24,
          br: false,
          fields: [
            {
              key: "select",
              label: "select",
              type: "select",
              required: true,
              editable: true,
              br: false,
              options: [
                { label: "test1", value: "test1" },
                { label: "test2", value: "test2" },
              ],
            },
            {
              key: "input1",
              label: "input1",
              required: true,
              br: false,
              allowClear: true,
            },
            {
              key: "input2",
              label: "input2",
              type: "input2",
              required: true,
              br: false,
              allowClear: true,
            },
          ],
        },
        {
          key: "input",
          placeholder: "input",
          type: "input",
          required: true,
          br: false,
          allowClear: true,
          style: { width: "100%" },
        },
        {
          key: "input2",
          placeholder: "input2",
          type: "input",
          required: true,
          br: false,
          allowClear: true,
          style: { width: "100%" },
        },
        {
          key: "switch",
          placeholder: "switch",
          type: "switch",
          required: true,
          editable: true,
          br: false,
        },
        {
          key: "textarea",
          placeholder: "textarea",
          type: "textarea",
          required: true,
          br: false,
          allowClear: true,
          span: 24,
          style: { width: "100%" },
        },
        {
          type: "inputGroup",
          span: 24,
          br: true,
          fields: [
            {
              key: "select",
              label: "select",
              type: "select",
              required: true,
              editable: true,
              br: false,
              options: [
                { label: "test1", value: "test1" },
                { label: "test2", value: "test2" },
              ],
            },
            {
              key: "input1",
              label: "input1",
              type: "input",
              required: true,
              br: false,
              allowClear: true,
            },
            {
              key: "input2",
              label: "input2",
              type: "input2",
              required: true,
              br: false,
              allowClear: true,
            },
          ],
        },
      ],
    },
    {
      label: "inputGroup1",
      type: "inputGroup",
      span: 24,
      br: true,
      fields: [
        {
          key: "select",
          label: "select",
          type: "select",
          required: true,
          editable: true,
          br: false,
          options: [
            { label: "test1", value: "test1" },
            { label: "test2", value: "test2" },
          ],
        },
        {
          key: "input1",
          label: "input1",
          type: "input",
          required: true,
          br: false,
          allowClear: true,
        },
        {
          key: "input2",
          label: "input2",
          type: "input2",
          required: true,
          br: false,
          allowClear: true,
        },
      ],
    },
    {
      label: "inputGroup2",
      type: "inputGroup",
      required: true,
      editable: true,
      span: 24,
      br: true,
      fields: [
        {
          key: "cascader",
          label: "cascader",
          type: "cascader",
          options: [
            {
              label: "test1",
              value: "test1",
              children: [{ label: "test2", value: "test2" }],
            },
          ],
          required: true,
          editable: true,
          br: false,
        },
        {
          key: "datePicker",
          label: "datePicker",
          type: "datePicker",
          required: true,
          editable: true,
          br: false,
        },
        {
          key: "monthPicker",
          label: "monthPicker",
          type: "monthPicker",
          required: true,
          editable: true,
          br: false,
        },
        {
          key: "weekPicker",
          label: "weekPicker",
          type: "weekPicker",
          required: true,
          editable: true,
          br: false,
        },
      ],
    },
    {
      label: "inputGroup3",
      type: "inputGroup",
      span: 24,
      br: true,
      fields: [
        {
          key: "autoComplete",
          label: "autoComplete",
          type: "autoComplete",
          dataSource: ["11111", "test1111"],
          required: true,
          editable: true,
          br: false,
        },
        {
          key: "rangePicker",
          label: "rangePicker",
          type: "rangePicker",
          required: true,
          editable: true,
          br: false,
        },
        {
          key: "inputNumber",
          label: "inputNumber",
          type: "inputNumber",
          required: true,
          editable: true,
          br: false,
        },
      ],
    },
  ],
}

// for (let i = 0; i <= 100; i++) {
//   demoProps.fields.push({
//     key: "input-" + i,
//     label: "input-" + i,
//     type: "input",
//     required: true,
//   })
// }
